production:
  app: westend-admin-tools
  repo: https://git.heroku.com/westend-admin-tools.git
  config:
    BUNDLE_WITHOUT: "development:test"

staging:
  app: westend-admin-tools-staging
  repo: https://git.heroku.com/westend-admin-tools-staging.git
  config: &default
    BUNDLE_WITHOUT: "development:test"